-- Canonical data and trust boundary. All writes with side effects go through RPCs.
create table public.profiles(id uuid primary key references auth.users(id),name text not null default 'Babson student' check(char_length(name) between 2 and 80),interests text[] not null default '{}',reminders boolean not null default true,role text not null default 'student' check(role in ('student','moderator')),created_at timestamptz not null default now());
create table public.organizers(id uuid primary key default gen_random_uuid(),name text not null,owner_id uuid references profiles(id));
create table public.venues(id uuid primary key default gen_random_uuid(),name text not null,address text);
create table public.sources(id uuid primary key default gen_random_uuid(),name text not null,url text not null,kind text not null check(kind in ('ics','rss','web','email','submission')),enabled boolean not null default false,last_checked_at timestamptz,last_success_at timestamptz,last_error text);
create table public.events(id uuid primary key default gen_random_uuid(),title text not null check(char_length(title) between 4 and 100),description text not null check(char_length(description) between 15 and 3000),category text not null check(category in ('Social','Food & drink','Sports & outdoors','Arts & culture','Learning','Wellness')),host_id uuid references profiles(id),organizer_id uuid references organizers(id),venue_id uuid references venues(id),provenance_url text,source_id uuid references sources(id),location text not null check(char_length(location) between 3 and 200),kind text not null check(kind in ('student','campus')),cost numeric not null default 0 check(cost between 0 and 1000),expectations text not null check(char_length(expectations) between 5 and 1000),cancellation_policy text not null check(char_length(cancellation_policy) between 5 and 500),status text not null default 'published' check(status in ('published','hidden','cancelled')),verified_at timestamptz not null default now(),created_at timestamptz not null default now(),version integer not null default 1);
create table public.occurrences(id uuid primary key default gen_random_uuid(),event_id uuid not null unique references events(id),starts_at timestamptz not null,ends_at timestamptz not null,capacity integer not null check(capacity between 2 and 500),check(ends_at>starts_at));
create table public.tags(id bigint generated always as identity primary key,label text not null unique);
create table public.event_tags(event_id uuid references events(id),tag_id bigint references tags(id),primary key(event_id,tag_id));
create table public.attendance(event_id uuid references events(id),user_id uuid references profiles(id),status text not null check(status in ('joined','waitlisted')),queued_at timestamptz not null default clock_timestamp(),primary key(event_id,user_id));
create index attendance_queue on attendance(event_id,status,queued_at,user_id);
create table public.saves(event_id uuid references events(id),user_id uuid references profiles(id),primary key(event_id,user_id));
create table public.blocks(user_id uuid references profiles(id),blocked_id uuid references profiles(id),primary key(user_id,blocked_id),check(user_id<>blocked_id));
create table public.announcements(id uuid primary key default gen_random_uuid(),event_id uuid not null references events(id),author_id uuid not null references profiles(id),body text not null check(char_length(body) between 5 and 1000),created_at timestamptz not null default now());
create table public.reports(id uuid primary key default gen_random_uuid(),event_id uuid references events(id),reporter_id uuid not null references profiles(id),reason text not null check(reason in ('safety','harassment','incorrect','spam')),details text not null check(char_length(details) between 10 and 2000),status text not null default 'open' check(status in ('open','resolved')),created_at timestamptz not null default now(),unique(event_id,reporter_id));
create table public.audit_log(id bigint generated always as identity primary key,actor_id uuid,event_id uuid references events(id),action text not null,details jsonb not null default '{}',created_at timestamptz not null default now());
create table public.event_status_history(id bigint generated always as identity primary key,event_id uuid references events(id),status text not null,actor_id uuid,created_at timestamptz not null default now());
create table public.import_drafts(id uuid primary key default gen_random_uuid(),source_id uuid references sources(id),submitted_by uuid references profiles(id),external_id text,fingerprint text not null,content_hash text not null default '',payload jsonb not null,raw jsonb not null,confidence numeric not null check(confidence between 0 and 1),status text not null default 'review' check(status in ('review','published','rejected','duplicate')),published_event_id uuid references events(id),duplicate_of uuid references events(id),created_at timestamptz not null default now(),unique(source_id,fingerprint,content_hash));
create table public.notifications(id uuid primary key default gen_random_uuid(),user_id uuid not null references profiles(id),event_id uuid references events(id),kind text not null,message text not null,dedupe_key text not null unique,created_at timestamptz not null default now(),read_at timestamptz);
create table public.deliveries(notification_id uuid primary key references notifications(id),status text not null default 'pending' check(status in ('pending','sending','delivered','failed')),attempts integer not null default 0,claimed_at timestamptz,delivered_at timestamptz,provider_id text,last_error text);
create table public.analytics(id bigint generated always as identity primary key,user_id uuid references profiles(id),event_id uuid references events(id),action text not null check(action in ('view','join','leave','create','cancel','check_in','no_show')),created_at timestamptz not null default now());

create function public.is_verified() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from auth.users where id=auth.uid() and email_confirmed_at is not null and email ~* '^[^\s@]+@babson\.edu$')$$;
create function public.is_moderator() returns boolean language sql stable security definer set search_path=public as $$select public.is_verified() and exists(select 1 from profiles where id=auth.uid() and role='moderator')$$;
create function public.require_student() returns uuid language plpgsql stable security definer set search_path=public as $$begin if not public.is_verified() then raise exception 'Verified Babson email required';end if;return auth.uid();end$$;
create function public.bootstrap_profile() returns trigger language plpgsql security definer set search_path=public as $$begin if new.email ~* '^[^\s@]+@babson\.edu$' then insert into profiles(id) values(new.id) on conflict do nothing;end if;return new;end$$;
create trigger auth_profile after insert or update of email_confirmed_at on auth.users for each row execute function public.bootstrap_profile();
create function public.can_view_event(eid uuid) returns boolean language sql stable security definer set search_path=public as $$select is_verified() and exists(select 1 from events e where e.id=eid and (is_moderator() or e.host_id=auth.uid() or (e.status in ('published','cancelled') and not exists(select 1 from blocks b where (b.user_id=auth.uid() and b.blocked_id=e.host_id) or (b.blocked_id=auth.uid() and b.user_id=e.host_id)))))$$;
create function public.seats_left(eid uuid) returns integer language sql stable security definer set search_path=public as $$select case when can_view_event(eid) then (select greatest(0,o.capacity-(select count(*)::integer from attendance a where a.event_id=eid and a.status='joined')) from occurrences o where o.event_id=eid) else null end$$;

-- Enable RLS on every table, including queues and internal audit records.
do $$declare t text;begin foreach t in array array['profiles','organizers','venues','sources','events','occurrences','tags','event_tags','attendance','saves','blocks','announcements','reports','audit_log','event_status_history','import_drafts','notifications','deliveries','analytics'] loop execute format('alter table public.%I enable row level security',t);end loop;end$$;
create policy profiles_read on profiles for select using(is_verified());
create policy profiles_update on profiles for update using(id=auth.uid() and is_verified()) with check(id=auth.uid() and is_verified());
create policy organizers_read on organizers for select using(is_verified());
create policy venues_read on venues for select using(is_verified());
create policy sources_read on sources for select using(is_verified());
create policy events_read on events for select using(can_view_event(id));
create policy occurrences_read on occurrences for select using(can_view_event(event_id));
create policy tags_read on tags for select using(is_verified());
create policy event_tags_read on event_tags for select using(can_view_event(event_id));
create policy attendance_read on attendance for select using(is_verified() and (user_id=auth.uid() or exists(select 1 from events e where e.id=event_id and e.host_id=auth.uid())));
create policy saves_own on saves for all using(is_verified() and user_id=auth.uid()) with check(is_verified() and user_id=auth.uid() and can_view_event(event_id));
create policy blocks_read on blocks for select using(is_verified() and user_id=auth.uid());
create policy announcements_read on announcements for select using(can_view_event(event_id));
create policy reports_read on reports for select using(is_verified() and (reporter_id=auth.uid() or is_moderator()));
create policy audit_read on audit_log for select using(is_moderator());
create policy history_read on event_status_history for select using(can_view_event(event_id));
create policy drafts_read on import_drafts for select using(is_moderator() or (is_verified() and submitted_by=auth.uid()));
create policy drafts_submit on import_drafts for insert with check(is_verified() and submitted_by=auth.uid() and status='review' and published_event_id is null and duplicate_of is null and source_id is null);
create policy notices_read on notifications for select using(is_verified() and user_id=auth.uid());
create policy notices_update on notifications for update using(is_verified() and user_id=auth.uid()) with check(user_id=auth.uid());
create policy deliveries_read on deliveries for select using(is_moderator());
create policy analytics_read on analytics for select using(is_moderator());

create view public.event_feed with(security_invoker=true) as select e.*,o.starts_at,o.ends_at,o.capacity,coalesce(org.name,p.name,'Campus organizer') as organizer,coalesce(s.name,case when e.kind='student' then 'Student hosted' else 'Community curation' end) as source_name,coalesce(s.url,e.provenance_url) as source_url,seats_left(e.id) as seats_left from events e join occurrences o on o.event_id=e.id left join profiles p on p.id=e.host_id left join organizers org on org.id=e.organizer_id left join sources s on s.id=e.source_id;

create function public.log_event() returns trigger language plpgsql security definer set search_path=public as $$begin insert into audit_log(actor_id,event_id,action,details) values(auth.uid(),new.id,TG_OP,jsonb_build_object('status',new.status,'version',new.version,'record',to_jsonb(new)));if TG_OP='INSERT' or old.status is distinct from new.status then insert into event_status_history(event_id,status,actor_id) values(new.id,new.status,auth.uid());end if;return new;end$$;
create trigger events_audit after insert or update on events for each row execute function log_event();
create function public.create_activity(input jsonb) returns uuid language plpgsql security definer set search_path=public as $$declare uid uuid:=require_student();eid uuid;begin
 if (select count(*) from events where host_id=uid and created_at>now()-interval '1 day')>=10 then raise exception 'Daily hosting limit reached';end if;
 if (input->>'starts_at')::timestamptz<=now() then raise exception 'Choose a future start';end if;
 insert into events(title,description,category,host_id,location,kind,cost,expectations,cancellation_policy) values(input->>'title',input->>'description',input->>'category',uid,input->>'location','student',(input->>'cost')::numeric,input->>'expectations',input->>'cancellation_policy') returning id into eid;
 insert into occurrences(event_id,starts_at,ends_at,capacity) values(eid,(input->>'starts_at')::timestamptz,(input->>'ends_at')::timestamptz,(input->>'capacity')::integer);
 insert into attendance(event_id,user_id,status) values(eid,uid,'joined');insert into analytics(user_id,event_id,action) values(uid,eid,'create');return eid;end$$;
create function public.join_activity(eid uuid) returns text language plpgsql security definer set search_path=public as $$declare uid uuid:=require_student();e events;o occurrences;result text;begin
 select * into e from events where id=eid for update;if not found or not can_view_event(eid) or e.status<>'published' then raise exception 'Activity unavailable';end if;
 select * into o from occurrences where event_id=eid;if o.starts_at<=now() then raise exception 'Activity has already started';end if;
 select status into result from attendance where event_id=eid and user_id=uid;if found then return result;end if;
 if (select count(*) from attendance where event_id=eid and status='joined')<o.capacity then result:='joined';else result:='waitlisted';end if;
 insert into attendance(event_id,user_id,status) values(eid,uid,result);insert into analytics(user_id,event_id,action) values(uid,eid,'join');return result;end$$;
create function public.leave_activity(eid uuid) returns void language plpgsql security definer set search_path=public as $$declare uid uuid:=require_student();e events;old_status text;promoted uuid;begin
 select * into e from events where id=eid for update;if not found then raise exception 'Unknown activity';end if;if e.host_id=uid then raise exception 'Hosts must cancel their activity';end if;
 delete from attendance where event_id=eid and user_id=uid returning status into old_status;if old_status is null then return;end if;
 insert into analytics(user_id,event_id,action) values(uid,eid,'leave');
 if old_status='joined' and e.status='published' and exists(select 1 from occurrences where event_id=eid and starts_at>now()) then
 select a.user_id into promoted from attendance a join auth.users u on u.id=a.user_id where a.event_id=eid and a.status='waitlisted' and u.email_confirmed_at is not null and u.email ~* '^[^\s@]+@babson\.edu$' and not exists(select 1 from blocks b where (b.user_id=a.user_id and b.blocked_id=e.host_id) or (b.blocked_id=a.user_id and b.user_id=e.host_id)) order by a.queued_at,a.user_id limit 1;
 if promoted is not null then update attendance set status='joined' where event_id=eid and user_id=promoted;insert into notifications(user_id,event_id,kind,message,dedupe_key) values(promoted,eid,'promotion','A spot opened up! You are now joining '||e.title,'promotion:'||eid||':'||promoted||':'||clock_timestamp());end if;end if;end$$;
create function public.notify_change(eid uuid,kind text,body text,key text) returns void language sql security definer set search_path=public as $$insert into notifications(user_id,event_id,kind,message,dedupe_key) select user_id,eid,kind,body,key||':'||user_id from (select user_id from attendance where event_id=eid union select user_id from saves where event_id=eid) recipients on conflict(dedupe_key) do nothing$$;
create function public.cancel_activity(eid uuid) returns void language plpgsql security definer set search_path=public as $$declare uid uuid:=require_student();e events;begin select * into e from events where id=eid for update;if e.host_id is distinct from uid and not is_moderator() then raise exception 'Only the host can cancel';end if;if e.status='cancelled' then return;end if;update events set status='cancelled',version=version+1 where id=eid;perform notify_change(eid,'cancellation',e.title||' has been cancelled.','cancel:'||eid);insert into analytics(user_id,event_id,action) values(uid,eid,'cancel');end$$;
create function public.post_announcement(eid uuid,body text) returns void language plpgsql security definer set search_path=public as $$declare uid uuid:=require_student();aid uuid;begin if not exists(select 1 from events where id=eid and host_id=uid and status='published') then raise exception 'Only the host can announce';end if;insert into announcements(event_id,author_id,body) values(eid,uid,body) returning id into aid;perform notify_change(eid,'announcement',body,'announcement:'||aid);insert into audit_log(actor_id,event_id,action) values(uid,eid,'announcement');end$$;
create function public.report_event(eid uuid,reason text,details text) returns void language plpgsql security definer set search_path=public as $$declare uid uuid:=require_student();begin if not can_view_event(eid) then raise exception 'Activity unavailable';end if;if (select count(*) from reports where reporter_id=uid and created_at>now()-interval '1 day')>=5 then raise exception 'Daily report limit reached';end if;insert into reports(event_id,reporter_id,reason,details) values(eid,uid,reason,details);if reason in ('safety','harassment') then update events set status='hidden',version=version+1 where id=eid;perform notify_change(eid,'safety','An activity in your plans is temporarily unavailable while reviewed.','safety:'||eid||':'||(select version from events where id=eid));end if;insert into audit_log(actor_id,event_id,action,details) values(uid,eid,'report',jsonb_build_object('reason',reason));end$$;
create function public.block_student(target uuid) returns void language plpgsql security definer set search_path=public as $$declare uid uuid:=require_student();eid uuid;begin insert into blocks(user_id,blocked_id) values(uid,target) on conflict do nothing;for eid in select a.event_id from attendance a join events e on e.id=a.event_id where a.user_id=uid and e.host_id=target loop perform leave_activity(eid);end loop;insert into audit_log(actor_id,action,details) values(uid,'block',jsonb_build_object('target',target));end$$;
create function public.moderate_event(eid uuid,resolution text,note text) returns void language plpgsql security definer set search_path=public as $$begin if not is_moderator() then raise exception 'Moderator required';end if;if resolution not in ('published','cancelled','hidden') or char_length(note)<10 then raise exception 'Provide a resolution and reason';end if;perform 1 from events where id=eid for update;if resolution='cancelled' then perform cancel_activity(eid);else update events set status=resolution,version=version+1 where id=eid;end if;update reports set status='resolved' where event_id=eid;insert into audit_log(actor_id,event_id,action,details) values(auth.uid(),eid,'moderate',jsonb_build_object('resolution',resolution,'note',note));end$$;
create function public.track_event(eid uuid,action text) returns void language plpgsql security definer set search_path=public as $$declare uid uuid:=require_student();begin if action not in ('view','check_in','no_show') or not can_view_event(eid) then raise exception 'Invalid analytics event';end if;if action in ('check_in','no_show') and not exists(select 1 from attendance a join occurrences o on o.event_id=a.event_id where a.user_id=uid and a.event_id=eid and a.status='joined' and o.starts_at<=now() and o.ends_at>now()-interval '7 days') then raise exception 'Attendance confirmation unavailable';end if;if not exists(select 1 from analytics a where a.user_id=uid and a.event_id=eid and a.action=track_event.action and a.created_at>now()-interval '1 day') then insert into analytics(user_id,event_id,action) values(uid,eid,action);end if;end$$;

-- In-app notice creation is transactional. Email delivery uses a leased outbox.
create function public.enqueue_reminders() returns integer language plpgsql security definer set search_path=public as $$declare n integer;begin insert into notifications(user_id,event_id,kind,message,dedupe_key) select a.user_id,e.id,'reminder','Coming up: '||e.title||' at '||e.location,'reminder:'||e.id||':'||a.user_id||':'||o.starts_at from attendance a join events e on e.id=a.event_id join occurrences o on o.event_id=e.id join profiles p on p.id=a.user_id where a.status='joined' and p.reminders and e.status='published' and o.starts_at>now() and o.starts_at<=now()+interval '24 hours' on conflict(dedupe_key) do nothing;get diagnostics n=row_count;insert into deliveries(notification_id) select n.id from notifications n join profiles p on p.id=n.user_id where p.reminders on conflict do nothing;return n;end$$;
create function public.claim_deliveries() returns table(notification_id uuid,email text,message text) language plpgsql security definer set search_path=public as $$begin return query with batch as(select d.notification_id from deliveries d join notifications n on n.id=d.notification_id join profiles p on p.id=n.user_id join auth.users u on u.id=p.id where p.reminders and u.email_confirmed_at is not null and u.email ~* '^[^\s@]+@babson\.edu$' and n.created_at>now()-interval '23 hours' and (n.kind<>'reminder' or exists(select 1 from events current_event join occurrences current_occurrence on current_occurrence.event_id=current_event.id where current_event.id=n.event_id and current_event.status='published' and current_occurrence.starts_at>now() and n.dedupe_key='reminder:'||current_event.id||':'||n.user_id||':'||current_occurrence.starts_at)) and d.attempts<5 and (d.status in ('pending','failed') or (d.status='sending' and d.claimed_at<now()-interval '10 minutes')) order by n.created_at limit 50 for update of d skip locked),claimed as(update deliveries d set status='sending',attempts=attempts+1,claimed_at=now() from batch b where d.notification_id=b.notification_id returning d.notification_id) select c.notification_id,u.email,n.message from claimed c join notifications n on n.id=c.notification_id join auth.users u on u.id=n.user_id;end$$;

-- Revoke default PUBLIC function privileges and grant only intended boundaries.
revoke all on all tables in schema public from anon,authenticated;
grant usage on schema public to anon,authenticated,service_role;
grant select on profiles,organizers,venues,sources,events,occurrences,tags,event_tags,event_feed,attendance,saves,blocks,announcements,reports,audit_log,event_status_history,import_drafts,notifications,deliveries,analytics to authenticated;
grant select on profiles,organizers,sources,events,occurrences,event_feed to anon;
grant update(name,interests,reminders) on profiles to authenticated;
grant select,insert,delete on saves to authenticated;
grant insert(source_id,submitted_by,external_id,fingerprint,content_hash,payload,raw,confidence,status) on import_drafts to authenticated;
grant update(read_at) on notifications to authenticated;
grant all on all tables in schema public to service_role;
grant usage,select on all sequences in schema public to service_role;
revoke execute on all functions in schema public from public,anon,authenticated;
grant execute on function is_verified(),is_moderator(),can_view_event(uuid),seats_left(uuid) to anon,authenticated;
grant execute on function create_activity(jsonb),join_activity(uuid),leave_activity(uuid),cancel_activity(uuid),post_announcement(uuid,text),report_event(uuid,text,text),block_student(uuid),moderate_event(uuid,text,text),track_event(uuid,text) to authenticated;
grant execute on all functions in schema public to service_role;
